### PR TITLE
Add support for the Negation('$not') operator

### PR DESCRIPTION
**Pull request by Raj725**
Add support for the Negation(`$not`) operator in PGVector

### CODE REVIEW

**Comment by Raj725** [comment]
cc: @eyurtsev

**Comment by eyurtsev** [comment]
@Raj725 awesome. Would you mind adding a unit test?

**Comment by Raj725** [comment]
> @Raj725 awesome. Would you mind adding a unit test?

Sure, I was busy, but I'll add the unit test as soon as possible. Thanks!

**Comment by eyurtsev** [comment]
@Raj725 Taking over

**Pull request merged**
